### ISSUE TITLE
⬆️ Switch to `Googlers-Repo/magisk-modules-repo-util`

### ISSUE THREAD

**Issue by Rikj000** [Rikj000/Magisk-Modules-Rikj000-Repo#1]
## Issue Description
[`MRepoApp/MRepo`](https://github.com/MRepoApp/MRepo) and [`MRepoApp/magisk-modules-repo-util`](https://github.com/MRepoApp/magisk-modules-repo-util) have been archived.

For this reason we should eventually switch to @DerGoogler's   
[`DerGoogler/MMRL`](https://github.com/DerGoogler/MMRL) and [`Googlers-Repo/magisk-modules-repo-util`](https://github.com/Googlers-Repo/magisk-modules-repo-util).

## Compatibility Notes
I won't switch [`MRepoApp/magisk-modules-repo-util`](https://github.com/MRepoApp/magisk-modules-repo-util) for [`Googlers-Repo/magisk-modules-repo-util`](https://github.com/Googlers-Repo/magisk-modules-repo-util) before ~~either~~:
- [`MRepoApp/magisk-modules-repo-util`](https://github.com/MRepoApp/magisk-modules-repo-util) breaks usage of [`DerGoogler/MMRL`](https://github.com/DerGoogler/MMRL)
- ~~[`Googlers-Repo/magisk-modules-repo-util`](https://github.com/Googlers-Repo/magisk-modules-repo-util) becomes backwards compatible with [`MRepoApp/MRepo`](https://github.com/MRepoApp/MRepo)~~

The reasoning behind this is to stay backwards compatible with [`MRepoApp/MRepo`](https://github.com/MRepoApp/MRepo) for as long as possible.   

I know that in it's current state [`Googlers-Repo/magisk-modules-repo-util`](https://github.com/Googlers-Repo/magisk-modules-repo-util) breaks compatibility with [`MRepoApp/MRepo`](https://github.com/MRepoApp/MRepo).   
However for the time being [`MRepoApp/magisk-modules-repo-util`](https://github.com/MRepoApp/magisk-modules-repo-util) is still supported   
by both [`MRepoApp/MRepo`](https://github.com/MRepoApp/MRepo) and [`DerGoogler/MMRL`](https://github.com/DerGoogler/MMRL).

**Comment by DerGoogler** [comment]
Latest version of MRepo doesn't even have the same repo format.   
And the fact that MMRL is now based on MRepo makes this issue useless. 

I do not take the effort to add backwards compatibility nor I have the time to add it.

**Comment by Rikj000** [comment]
> And the fact that MMRL is now based on MRepo makes this issue useless.

For me this issue is not useless, it's a reminder to eventually update to your [`Googlers-Repo/magisk-modules-repo-util`](https://github.com/Googlers-Repo/magisk-modules-repo-util).

> I do not take the effort to add backwards compatibility nor I have the time to add it.

That's reasonable / fine, good to know that backwards compatibility won't be added though.

**Comment by DerGoogler** [comment]
> For me this issue is not useless, it's a reminder to eventually update to your [`Googlers-Repo/magisk-modules-repo-util`](https://github.com/Googlers-Repo/magisk-modules-repo-util).

What is the problem actually? MMRL is still FOSS. Provided APIs like mmrl.dergoogler.com doesn't collect data. The app is the same.

**Comment by Rikj000** [comment]
> What is the problem actually?

- [`Rikj000/Magisk-Modules-Rikj000-Repo`](https://github.com/Rikj000/Magisk-Modules-Rikj000-Repo) still uses [`MRepoApp/magisk-modules-repo-util`](https://github.com/MRepoApp/magisk-modules-repo-util):   
   - Can be successfully imported in `MMRL`
   - Can be successfully imported in `MRepo`
- [`Googlers-Repo/gmr`](https://github.com/Googlers-Repo/gmr) already uses [`Googlers-Repo/magisk-modules-repo-util`](https://github.com/Googlers-Repo/magisk-modules-repo-util):
   - Can be successfully imported in `MMRL`
   - Crashes with following stack trace when attempting to import in `MRepo`
      ```log
      com.sanmer.mrepo.Ke: Expected a double but was NULL at path $.modules[6].track.added
      	at com.sanmer.mrepo.uz.s(Unknown Source:227)
      	at com.sanmer.mrepo.m30.a(Unknown Source:239)
      	at com.sanmer.mrepo.model.online.TrackJsonJsonAdapter.a(Unknown Source:149)
      	at com.sanmer.mrepo.zL.a(Unknown Source:15)
      	at com.sanmer.mrepo.model.online.OnlineModuleJsonAdapter.a(Unknown Source:87)
      	at com.sanmer.mrepo.zL.a(Unknown Source:15)
      	at com.sanmer.mrepo.Dd.f(Unknown Source:15)
      	at com.sanmer.mrepo.Dd.a(Unknown Source:0)
      	at com.sanmer.mrepo.zL.a(Unknown Source:15)
      	at com.sanmer.mrepo.model.online.ModulesJsonJsonAdapter.a(Unknown Source:44)
      	at com.sanmer.mrepo.zL.a(Unknown Source:15)
      	at com.sanmer.mrepo.hI.j(Unknown Source:31)
      	at com.sanmer.mrepo.PL.d(Unknown Source:55)
      	at com.sanmer.mrepo.PL.l(Unknown Source:24)
      	at com.sanmer.mrepo.fk.l(Unknown Source:2)
      	at com.sanmer.mrepo.AH.q(Unknown Source:76)
      	at com.sanmer.mrepo.y8.m(Unknown Source:8)
      	at com.sanmer.mrepo.El.run(Unknown Source:112)
      	at com.sanmer.mrepo.W0.run(Unknown Source:47)
      	at com.sanmer.mrepo.a60.run(Unknown Source:2)
      	at com.sanmer.mrepo.hi.run(Unknown Source:95)
      ```

> MMRL is still FOSS.

Dw, I love `MMRL` + your other work, and believe in it replacing `MRepo` going forward! 
I have already switched to `MMRL` personally :slightly_smiling_face:

However for the time being I'm just thinking about the users who are not aware yet of the `MRepo` archival,   
and thus trying to remain backwards compatible with it for as long as possible.

**Comment by DerGoogler** [comment]
> However for the time being I'm just thinking about the users who are not aware yet of the `MRepo` archival,
> and thus trying to remain backwards compatible with it for as long as possible.

I can look into it but I can't guarantee it for this year

**Comment by Rikj000** [comment]
> I can look into it but I can't guarantee it for this year

Only if you want to and have the time for it, it's FOSS / our hobby after all,   
needs to remain fun, not a 2nd job :slightly_smiling_face:

**Comment by DerGoogler** [comment]
I'm also currently working on make the blacklist, changelog, and recommended repositories more accessible

- https://mmrl.dergoogler.com/changelog
- https://mmrl.dergoogler.com/blacklist
- https://mmrl.dergoogler.com/repositories

**Comment by Rikj000** [comment]
> I'm also currently working on make the blacklist, changelog, and recommended repositories more accessible

That will be nice! Didn't know those pages existed, and they provide useful info :smile:
